name: manga_mania
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutterfire_cli: ^0.1.1+2
  flutter_riverpod: ^2.5.1
  provider: ^6.1.2
  file_picker: ^8.0.3
  mongo_dart: ^0.10.2
  open_file: ^3.3.2
  pdf: ^3.8.4
  http: ^1.2.1
  pdf_render: ^1.4.6
  firebase_storage: ^11.7.4
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  syncfusion_flutter_pdf: ^24.2.8
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^24.2.8
  pdfrx: ^1.0.61

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/pages/home/images/
    - lib/pdfs/